sudo: required
services:
  - docker

before_install:
  - docker build -t ea2sa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ea2sa/docker-react npm run test -- --coverage

language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-819295806321"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"